# Generated by Django 4.1 on 2023-03-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Excerpt', models.TextField()),
                ('image_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('Slug', models.SlugField(default='')),
                ('content', models.TextField()),
            ],
        ),
    ]
