# Generated by Django 4.1 on 2023-03-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_tag_alter_post_options_post_author_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='capation',
            new_name='caption',
        ),
    ]
